# Generated by Django 2.1.2 on 2018-12-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181107_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='worry',
            name='author',
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
        migrations.DeleteModel(
            name='Poem',
        ),
        migrations.DeleteModel(
            name='Worry',
        ),
    ]
