# Generated by Django 2.1.2 on 2018-12-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181209_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('education', models.CharField(max_length=200)),
                ('career', models.CharField(max_length=200)),
                ('introduce', models.TextField()),
                ('portfolio', models.URLField()),
            ],
        ),
    ]
