# Generated by Django 2.1.2 on 2018-12-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
